"""Añadida columna homeworld a People

Revision ID: 0c7b0f2289e1
Revises: 6c864683a95c
Create Date: 2025-01-01 19:15:23.441232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7b0f2289e1'
down_revision = '6c864683a95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.String(length=100), nullable=True))
        batch_op.drop_column('eye_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###
